Map<String, String> arEg = {
  'hello_world': 'مرحبا بك',
  'top_rating': 'أفضل 10 تقيما',
  'all_restaurant': 'كل المطاعم',
  'filter': 'تصفية',
  'offer': 'عرض',
  'grocery': 'بقالات',
  'my_order': 'طلباتي',
  'favorite': 'المفضلة',
  'my_profile': 'الصفحة الشخصية',
  'delivery_address': 'عناوين التوصيلات',
  'payment_method': 'طرق الدفع',
  'notifications': 'اشعارات',
  'vouchers_credit': 'القسائم والائتمان',
  'contact_us': 'اتصل بنا',
  'about_us': 'عنا',
  'logout': 'تسجيل خروج',
};
