Map<String, String> arEg = {
  'hello_world': 'مرحبا بك',
  'top_rating': 'أفضل 10 تقيما',
  'all_restaurant': 'كل المطاعم',
  'filter': 'تصفية',
  'offer': 'عرض',
  'grocery': 'بقالات',
  'my_order': 'طلباتي',
  'favorite': 'المفضلة',
  'my_profile': 'الصفحة الشخصية',
  'delivery_address': 'عناوين التوصيلات',
  'payment_method': 'طرق الدفع',
  'notifications': 'اشعارات',
  'vouchers_credit': 'القسائم والائتمان',
  'contact_us': 'اتصل بنا',
  'about_us': 'عنا',
  'logout': 'تسجيل خروج',
  'sort': 'ترتيب',
  'lowest_prices': 'أقل سعر',
  'delivery_free': 'ديليفري حر',
  'delivery_time': 'ديليفري وقت',
  'rating': 'تقييم',
  'popular_filters': 'التصفيات الشائعة',
  'provides_service': 'الخدمات الموفرة',
  'done': 'تم',
  'required': '*مطلوب',
  'email': 'بريد إلكتروني',
  'password': 'كلمة المرور',
  'click_here': 'اضغط هنا',
  'for_get_password': 'لاسترجاء كلمة المرور',
  'remember_me': 'ذكرني لاحقا',
  'login': 'تسجيل دخول',
  'login_by': 'تسجيل بواسطة',
  'please_waiting': 'من فضلك انتظر قليلا',
  'sign_up': 'انضمام إلينا',
  'invalid_email': 'البريد غير صحيح',
  'name': 'الاسم',
  'message_login': 'رجاء لكي تطلب يجب ان تسجل دخول',
  'password_not_matching': 'كلمة السر غير متطابقة',
  'registration_successfully': 'تم التسجيل بنجاح',
  'login_successfully': 'تم تسجيل دخول بنجاح',
  'internet_not_available': 'الانترنت غير متوفر',
  'order_number': 'رقم الطلب',
  'the_restaurant': 'المطعم',
  'time_order': 'وقت الطلب',
  'status': 'الحالة',
  'path': 'المسار',
  'view_details': 'التفاصيل',
  'number_of_meals': 'عدد الوجبات',
  'transporter': 'وسيلة النقل',
};
