Map<String, String> arEg = {
  'hello_world': 'مرحبا بك',
  'top_rating': 'أفضل 10 تقيما',
  'all_restaurant': 'كل المطاعم',
  'filter': 'تصفية',
  'offer': 'عرض',
  'grocery': 'بقالات',
  'sort': 'ترتيب',
  'lowest_prices': 'أقل سعر',
  'delivery_free': 'ديليفري حر',
  'delivery_time': 'ديليفري وقت',
  'rating': 'تقييم',
  'popular_filters': 'التصفيات الشائعة',
  'provides_service': 'الخدمات الموفرة',
  'done': 'تم',
  'required': '*مطلوب',
  'email': 'بريد إلكتروني',
  'password': 'كلمة المرور',
  'click_here': 'اضغط هنا',
  'for_get_password': 'لاسترجاء كلمة المرور',
  'remember_me': 'ذكرني لاحقا',
  'login': 'تسجيل دخول',
  'login_by': 'تسجيل بواسطة',
  'please_waiting': 'من فضلك انتظر قليلا',
};
