Map<String, String> enUs = {
  'hello_world': 'Holle World',
  'top_rating': 'Top 10 Rating',
  'all_restaurant': 'All Restaurant',
  'filter': 'Filter',
  'offer': 'Offer',
  'grocery': 'Grocery',
  'sort': 'Sort',
  'lowest_prices': 'Lowest Prices',
  'delivery_free': 'Delivery free',
  'delivery_time': 'Delivery Time',
  'rating': 'Rating',
  'popular_filters': 'Popular filters',
  'provides_service': 'Provides a service',
  'done': 'Done',
};
