Map<String, String> enUs = {
  'hello_world': 'Holle World',
  'top_rating': 'Top 10 Rating',
  'all_restaurant': 'All Restaurant',
  'filter': 'Filter',
  'offer': 'Offer',
  'grocery': 'Grocery',
  'my_order': 'My Order',
  'favorite': 'Favorite',
  'my_profile': 'My Profile',
  'delivery_address': 'Delivery address',
  'payment_method': 'Payment method',
  'notifications': 'Notifications',
  'vouchers_credit': 'Vouchers & credit',
  'contact_us': 'Contact us',
  'about_us': 'About us',
  'logout': 'Logout',
};
