Map<String, String> enUs = {
  'hello_world': 'Holle World',
  'top_rating': 'Top 10 Rating',
  'all_restaurant': 'All Restaurant',
  'filter': 'Filter',
  'offer': 'Offer',
  'grocery': 'Grocery',
  'sort': 'Sort',
  'lowest_prices': 'Lowest Prices',
  'delivery_free': 'Delivery free',
  'delivery_time': 'Delivery Time',
  'rating': 'Rating',
  'popular_filters': 'Popular filters',
  'provides_service': 'Provides a service',
  'done': 'Done',
  'required': '*Requried',
  'email': 'Email',
  'password': 'Password',
  'click_here': 'Click here',
  'for_get_password': 'For get your password ? ',
  'remember_me': 'Remember me',
  'login': 'Login',
  'login_by': 'Login by',
  'please_waiting': 'please waiting...',
  'sign_up': 'Sign up',
  'invalid_email': 'Invalid email',
  'name': 'Name',
  'mobile': 'Mobile',
  'confirm_password': 'Confirm Password',
  'message_login': 'please to order you must login',
  'password_not_matching': 'Password not matching',
  'registration_successfully': 'Registration successfully',
  'login_successfully': 'Login successfully',
  'internet_not_available': 'Internet not available ',
  'my_order': 'My Order',
  'favorite': 'Favorite',
  'my_profile': 'My Profile',
  'delivery_address': 'Delivery address',
  'payment_method': 'Payment method',
  'notifications': 'Notifications',
  'vouchers_credit': 'Vouchers & credit',
  'contact_us': 'Contact us',
  'about_us': 'About us',
  'logout': 'Logout',
  'order_number': 'Order number',
  'the_restaurant': 'The restaurant',
  'time_order': 'Time order',
  'status': 'Status',
  'path': 'Path',
  'view_details': 'View details',
  'number_of_meals': 'Number of meals',
};
